services:
    _defaults:
        autowire: true
        autoconfigure: true


    Becklyn\RouteTreeBundle\Builder\ParametersGenerator: ~
    Becklyn\RouteTreeBundle\Tree\RouteTree: ~


    # -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    # Post Processing
    # -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    Becklyn\RouteTreeBundle\PostProcessing\PostProcessor: ~
    Becklyn\RouteTreeBundle\PostProcessing\Processor\MissingParametersProcessor: ~

    Becklyn\RouteTreeBundle\PostProcessing\Processor\SecurityProcessor:
        arguments:
            $expressionLanguage: '@sensio_framework_extra.security.expression_language'
            $trustResolver: '@security.authentication.trust_resolver'
            $roleHierarchy: '@security.role_hierarchy'

    Becklyn\RouteTreeBundle\PostProcessing\Processor\TranslationsProcessor: ~


    # -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    # Twig
    # -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    Becklyn\RouteTreeBundle\Twig\RouteTreeTwigExtension: ~


    # -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    # KnpMenu Integration
    # -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    Becklyn\RouteTreeBundle\KnpMenu\MenuBuilder: ~


    # -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    # Nodes
    # -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    Becklyn\RouteTreeBundle\Node\NodeFactory: ~

    # -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    # Nodes Provider
    # -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    Becklyn\RouteTreeBundle\Builder\TreeBuilder: ~

    Becklyn\RouteTreeBundle\Cache\TreeCache:
        $debug: '%kernel.debug%'
