services:
    _defaults:
        autowire: true
        autoconfigure: true

    Becklyn\RouteTreeBundle\:
        resource: '../../{Builder,Cache,KnpMenu,Node,PostProcessing,Tree,Twig}/*'

    Becklyn\RouteTreeBundle\Cache\TreeCache:
        $debug: '%kernel.debug%'

    Becklyn\RouteTreeBundle\Node\Security\SecurityInferHelper:
        arguments:
            $container: '@service_container'

    Becklyn\RouteTreeBundle\PostProcessing\Processor\SecurityProcessor:
        arguments:
            $expressionVoter: '@security.access.expression_voter'
