services:
    _defaults:
        autowire: true
        autoconfigure: true

    Becklyn\RouteTreeBundle\:
        resource: '../../{Builder,Cache,KnpMenu,Node,PostProcessing,Tree,Twig}/*'

    Becklyn\RouteTreeBundle\Cache\TreeCache:
        $debug: '%kernel.debug%'

    Becklyn\RouteTreeBundle\Node\Security\SecurityInferHelper:
        $container: '@service_container'

    Becklyn\RouteTreeBundle\PostProcessing\Processor\Security\SecurityChecker:
        $securityListener: '@sensio_framework_extra.security.listener'
