services:
    _defaults:
        autowire: true
        autoconfigure: true


    Becklyn\RouteTreeBundle\Tree\RouteTree: ~
    Becklyn\RouteTreeBundle\Builder\ParametersGenerator: ~


    # -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    # Post Processing
    # -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    Becklyn\RouteTreeBundle\Tree\Processing\PostProcessing: ~
    Becklyn\RouteTreeBundle\Tree\Processing\PostProcessing\TranslationsProcessor: ~
    Becklyn\RouteTreeBundle\Tree\Processing\PostProcessing\SecurityProcessor: ~
    Becklyn\RouteTreeBundle\Tree\Processing\PostProcessing\MissingParametersProcessor: ~


    # -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    # Twig
    # -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    Becklyn\RouteTreeBundle\Twig\RouteTreeTwigExtension: ~


    # -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    # KnpMenu Integration
    # -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    Becklyn\RouteTreeBundle\KnpMenu\MenuBuilder: ~


    # -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    # Nodes
    # -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    Becklyn\RouteTreeBundle\Node\NodeFactory: ~

    # -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    # Nodes Provider
    # -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    Becklyn\RouteTreeBundle\Cache\TreeCache:
        $debug: '%kernel.debug%'

    Becklyn\RouteTreeBundle\Builder\TreeBuilder: ~
