services:

    becklyn.route_tree:
        class: Becklyn\RouteTreeBundle\Tree\RouteTree
        arguments:
            - "@becklyn.route_tree.builder"
            - "@becklyn.route_tree.cache"
            - "@becklyn.route_tree.post_processing"
            - "@router"

    becklyn.route_tree.post_processing:
        class: Becklyn\RouteTreeBundle\Tree\Processing\PostProcessing
        arguments:
            - "@translator"
            - "@becklyn.route_tree.post_processing.security"
            - "@request_stack"

    becklyn.route_tree.post_processing.security:
        class: Becklyn\RouteTreeBundle\Tree\Processing\SecurityProcessor
        arguments:
            - "@security.token_storage"
            - "@security.authorization_checker"
            - "@sensio_framework_extra.security.expression_language"
            - "@security.authentication.trust_resolver"
            - "@security.role_hierarchy"
            - "@request_stack"

    becklyn.route_tree.builder.parameters_generator:
        class: Becklyn\RouteTreeBundle\Builder\ParametersGenerator



    # -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    # Twig
    # -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    becklyn.route_tree.twig.extension:
            class: Becklyn\RouteTreeBundle\Twig\RouteTreeTwigExtension
            arguments:
                - "@knp_menu.menu_provider"
                - "@knp_menu.renderer_provider"
                - "@becklyn.route_tree.knp_menu.menu_builder"
            tags:
                - { name: twig.extension }


    # -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    # KnpMenu Integration
    # -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    becklyn.route_tree.knp_menu.menu_builder:
        class: Becklyn\RouteTreeBundle\KnpMenu\MenuBuilder
        arguments:
            - "@knp_menu.factory"
            - "@becklyn.route_tree"


    # -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    # Nodes Provider
    # -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    becklyn.route_tree.cache:
        class: Becklyn\RouteTreeBundle\Cache\TreeCache

    becklyn.route_tree.builder:
        class: Becklyn\RouteTreeBundle\Builder\TreeBuilder
        arguments:
            - "@becklyn.route_tree.builder.parameters_generator"
