language: php

git:
    depth: 1

php:
    - 5.6
    - 7.0

before_install:
    - composer self-update --stable

install:
    - composer install

script:
    - ./vendor/bin/phpunit -c phpunit.xml --coverage-text
