language: php

git:
    depth: 1

php:
    - 7.1
    - 7.2

before_install:
    - composer self-update --stable

install:
    - composer install

script:
    - ./vendor/bin/phpunit -c phpunit.xml --coverage-clover=coverage.clover
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
