services:
    _defaults:
        autowire: true
        autoconfigure: true

    Becklyn\RouteTreeBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Exception,Resources,BecklynRouteTreeBundle.php}'

    Becklyn\RouteTreeBundle\Cache\TreeCache:
        $debug: '%kernel.debug%'

    Becklyn\RouteTreeBundle\Node\Security\SecurityInferHelper:
        $container: '@service_container'
