services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $isDebug: '%kernel.debug%'

    Becklyn\RouteTreeBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Exception,Resources,BecklynRouteTreeBundle.php}'

    Becklyn\RouteTreeBundle\Node\Security\SecurityInferHelper:
        $container: '@service_container'
